name: pipeline cd market mail

on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main

jobs:
    build_and_deliver:
        runs-on: ubuntu-latest

        steps:
          - name: fazendo clone do repositorio
            uses: actions/checkout@v3
            
          - name: configurando python
            uses: actions/setup-python@v4
            with:
              python-version:'3.12'
        
          - name: instalando dependências
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
      
          - name: rodando os testes
            run: pytest